config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :pictures
  get 'user/index'

  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'posts#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
    belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def index
    end

    def new
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new
    end 


    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(comment_params)
        @comment.user_id = current_user.id
        if @comment.save 
            redirect_to @post, notice: 'Comment accept.'
        else
            redirect_to posts_path, notice: 'Comment don`t accept.'
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        comment = @post.comments.find(params[:id])
        comment.destroy
        redirect_to @post
    end

private

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:comment, :name, :content_type, :data)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = User.all
    @comment = @post.comments.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json   
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :title, :user_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    #before_action only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!
  def index
  	@users = User.all

    respond_to do |format|
      format.html {}
      format.json { render json: @users}
    end

  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


end



class UsersController < ApplicationController
  before_filter :authenticate_user!
    
  def index
    @users = User.all
    respond_to do |format|
      format.html {}
      format.json { render json: @users}
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @user = User.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver_now
        format.html { redirect_to @user, notice: 'Question was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Question was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Question was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit( :email)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= form_for [@post, @comment] do |f| %>

	<div class="form-group">
	    <%= f.label :Comment %>
	    <%= f.text_field :body %>
	</div>

    <div class="form-group">
        <%= f.submit%>
    </div>

<% end %>

app/views/hello/hello.html.erb
<strong>Hello,<%= user.email %>! Welcome to my site.</strong>

app/views/hello/hello.txt.erb
Hello,<%= user.email %>! Welcome to my site.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%=stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id = "panel">
  <h1><%= link_to "Blog", welcome_index_path %></h1>
    <% if current_user%>
    <div id = "config">
        <%= link_to image_tag("users.png", height: '25', width: '25'), user_index_path  %>
        <%= link_to image_tag("conf.png", height: '25', width: '25'), edit_user_registration_path  %>
        <%= link_to image_tag("exit.png", height: '25', width: '25'), destroy_user_session_path, method: :delete %>
    </div>
    <% end %>
</div>

<%if false%>
<div class="notice"><%= notice %></div>
<%end%>

<%if current_user%>
    <div id = "bar">
        <div id = "menu">
          <div class = "button"><%= link_to "Users",user_index_path%></div>
          <div class = "button"><%= link_to "Posts", posts_path%> </div>
          <div class = "button"><%= link_to "New post", new_post_path%></div>
        </div>
    </div>     
<%end%>

<div id = "container">
  <%= yield %>
</div>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.text_field :content_type %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Name</th>
      <th>Content type</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.comment %></td>
        <td><%= picture.name %></td>
        <td><%= picture.content_type %></td>
        <td><%= picture.data %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @picture.comment %>
</p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @picture.content_type %>
</p>

<p>
  <strong>Data:</strong>
  <%= @picture.data %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, size: 27 %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 6, cols: 40 %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Editing Post</h2>

<%= render 'form' %>


<label for="body"></label>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Posts</h2>


<% @posts.each do |post| %>
<!---      <tr>
        <td><%= post.user.email %></td>
        <td><%= post.title %></td>
        <td><%= truncate(strip_tags(post.body), length: 80) %></td>
        <td><%= link_to 'Show', post %></td>
        <%if post.user.email==current_user.email or current_user.id==1%>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr> -->
  <div class = "one">
    <strong><%= link_to "#{post.title}", post %></strong><br>
    <small><%= post.user.email %>, <%= post.created_at %></small><br>    
    <%= truncate(strip_tags(post.body), length: 80) %>
  </div>
  <br>
<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

<ul class="pager">
  <li class="previous"><%= link_to 'Back', posts_path %></li>
</ul>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<p id="notice"><%= notice %></p>

<div id = "post">
  <div id = "body">
  <%= sanitize @post.body %>
  </div>

  <div id = "info">
    <%= @post.user.email %>|
    <%= @post.created_at %>|
    <%if @post.user.email==current_user.email or current_user.id==1%>
      <%= link_to 'Edit', edit_post_path(@post) %> | <%= link_to 'Delete',  @post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <%end%>
  </div>
</div>

<br>
<div id = "comments">
  <strong>Cooments: </strong>

  <% @post.comments.each do |comment|%>
    <br>
    <%  user = @user.where(id: comment.user_id) %>
    <%= user[0].email unless user.empty? %>
    <br>
    <%= comment.body %> <br>
    <%= comment.created_at%><br>
    <%= link_to 'delete',[@post,comment], method: :delete unless comment.body==nil%>
  <%end%>
</div>

<%#= @post.id %>


<%= form_for [@post, @comment] do |f| %>

  <div class="form-group">
      <%= f.label %s{ Leave your comment:}  %><br>
      <%= f.text_area :body, rows: 4, cols: 40 %>
  </div>
  <%= f.submit%> 

<% end %>


<%#= link_to 'Comment_new', new_post_comment_path(@post) %>

<%= link_to 'Back', posts_path %>

app/views/user/index.html.erb
<h2>Listing Users</h2>

<table class="table-condensed">
  <thead>
    <tr>
      <th>Id</th>
      <th>Email</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
      <td><%= user.id %></td>
      <td><%= user.email %></td>   
      </tr>
    <% end %>
  </tbody>
</table>
<ul class="pager">
  <li class="previous"><%= link_to 'Back', posts_path %></li>
</ul>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>